# Generated by Django 3.2.7 on 2022-04-05 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_account',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='security_answer',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='security_question',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='userCode',
        ),
    ]
